default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    begin
      sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons --verbose"
    rescue => e
      UI.error("Flutter build failed: #{e.message}")
      raise e
    end
    firebase_app_distribution(
      app: "1:607640600832:android:0d1af1d198e72f2affb3e5",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "jofahmy8@gmail.com",
      release_notes: "First Distribution with fastlane"
    )
  end
end
