name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.4"
        bundler-cache: true
        working-directory: android

    - name: Install Bundler
      run: gem install bundler

    - name: Install Dependencies
      run: |
        cd android
        bundle install

    - name: Check Ruby and Bundler versions
      run: |
        ruby -v
        bundler -v
        bundle list
      working-directory: android

    - name: Debug Bundler Configuration
      run: |
        cd android
        bundle config
        bundle exec fastlane --version

    - name: Check Environment Variables
      run: printenv

    - name: List Files in Android Directory
      run: |
        ls -al android

    - name: Display Gemfile Content
      run: |
        cat android/Gemfile

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distribution
      working-directory: android
